@TodoAPI_HostAddress = https://localhost:7179

POST {{TodoAPI_HostAddress}}/api/todoitems
Content-Type: application/json

{
 "name": "Pedro Zeferino Bittencourt",
 "email": "pedro.zeferinob@gmail.com",
 "isComplete" : true
}



###

GET {{TodoAPI_HostAddress}}/api/todoitems

###

@id=4
GET {{TodoAPI_HostAddress}}/api/todoitems/{{id}}

###

POST {{TodoAPI_HostAddress}}/api/todoitems
Content-Type: application/json

{
 "name" : "Ana Luisa Miguel Paterno Lima",
"email" : "aninhaplima@gmail.com",
 "isComplete" : true
}

###
@id=2
DELETE {{TodoAPI_HostAddress}}/api/todoitems/{{id}}

###

PUT {{TodoAPI_HostAddress}}/api/todoitems/1
Content-Type: application/json

{
"id": 1,
"name": "Régis Bittencourt de Oliveira",
"email" : "regis.dsotm1973@gmail.com",
"isComplete" : true
}

###
